read -p "Management Cluster Name: " mgmt_cluster_name

rm .config/tanzu/tkg/clusterconfigs
mkdir .config/tanzu/tkg/clusterconfigs

rm .config/tanzu/tkg/clusterconfigs/${mgmt_cluster_name}.yaml
cat <<EOF | tee .config/tanzu/tkg/clusterconfigs/${mgmt_cluster_name}.yaml
AVI_CA_DATA_B64: ""
AVI_CLOUD_NAME: ""
AVI_CONTROL_PLANE_HA_PROVIDER: ""
AVI_CONTROLLER: ""
AVI_DATA_NETWORK: ""
AVI_DATA_NETWORK_CIDR: ""
AVI_ENABLE: "false"
AVI_LABELS: ""
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_CIDR: ""
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_NAME: ""
AVI_PASSWORD: ""
AVI_SERVICE_ENGINE_GROUP: ""
AVI_USERNAME: ""
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: $mgmt_cluster_name
CLUSTER_PLAN: dev
ENABLE_AUDIT_LOGGING: "false"
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "false"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: vsphere
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
OS_ARCH: amd64
OS_NAME: photon
OS_VERSION: "3"
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
TKG_IP_FAMILY: ipv4
VSPHERE_CONTROL_PLANE_DISK_GIB: "100"
VSPHERE_CONTROL_PLANE_ENDPOINT: 192.168.1.43
VSPHERE_CONTROL_PLANE_MEM_MIB: "32768"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "8"
VSPHERE_DATACENTER: /lab.home
VSPHERE_DATASTORE: /lab.home/datastore/primary-diskstore
VSPHERE_FOLDER: /lab.home/vm/tanzu
VSPHERE_INSECURE: "false"
VSPHERE_NETWORK: /lab.home/network/VM Network
VSPHERE_PASSWORD: <encoded:RzNuMyRpJEMjMVYuMQ==>
VSPHERE_RESOURCE_POOL: /lab.home/host/primary-cluster/Resources
VSPHERE_SERVER: vcenter-server.lab.home
VSPHERE_SSH_AUTHORIZED_KEY: AAAAB3NzaC1yc2EAAAADAQABAAABgQDNz6FLGtoSEBzAAlSrauCxhjaa7Sf4G3gzrH3NSjcM6bM51Ibvs94g0RknyZfLLEMBobTndIyiLknoJDNhuNcxke/bupY2aZ6Uf+jrkM+IJj3U8lE/otQg22/QZhiT08WLAg/bRlVK7i5q0K4zphJ5aGcTrHFkiuyAmJtNXP28vN/M5mVtRHXWHb7QQSQj5Z/F0MPw25NlXPj+Y7oWlt9Nv8UG7lnf4QoO6eHM9E2cKoj74RRpUBZvmEU/r9F67i5cPUHkNKybSWgfWG9eOw87hGc0Rty74H1sZBIt5tjgLgIR3bGrUGkQT8coBpY5UwDYTFc1L3sqOwV31kYp6Eeu2xChmztQMz3OOJDNzx8Bxb7W97yWZORL9fYEpqAzU48h/THk+VQ/pwJTkFdslDxKBeZWQtgbIEMqf1PMz9MOx74DfH6oJpd4pCVJFZFe+kT25eKTpW6jBcaQr/HKKVRg1y6RHlkIONoTBrsaoekGUmbgqQVMQbIieGW8H1YCwWc= mjames@tanzu-operator
VSPHERE_TLS_THUMBPRINT: E6:EF:B1:C9:66:0E:83:27:72:DF:C4:FD:47:89:DC:EE:3B:AA:BD:42
VSPHERE_USERNAME: administrator@vsphere.local
VSPHERE_WORKER_DISK_GIB: "100"
VSPHERE_WORKER_MEM_MIB: "32768"
VSPHERE_WORKER_NUM_CPUS: "8"
EOF

touch .kube/config

tanzu management-cluster create $mgmt_cluster_name --yes --deploy-tkg-on-vSphere7 --verbose 9 --timeout 1h -f .config/tanzu/tkg/clusterconfigs/${mgmt_cluster_name}.yaml
