policyList:
- meta:
    parentReferences:
    - rid: rid:org:86514df0-46a7-4b33-857d-954ba2970773
      uid: 86514df0-46a7-4b33-857d-954ba2970773
    uid: 86514df0-46a7-4b33-857d-954ba2970773
  roleBindings:
  - role: organization.credential.view
    subjects:
    - kind: GROUP
      name: tmc:member
  - role: organization.admin
    subjects:
    - kind: GROUP
      name: csp:org_owner
    - kind: GROUP
      name: tmc:admin
- meta:
    parentReferences:
    - rid: rid:cg:86514df0-46a7-4b33-857d-954ba2970773:cluster-group
      uid: cg:01FT6M0CGXW45QEHG6QMAA4G5Q
    uid: cg:01FT6M0CGXW45QEHG6QMAA4G5Q
  roleBindings:
  - role: clustergroup.view
    subjects:
    - kind: USER
      name: mjames@developerthejameshome.onmicrosoft.com



policyList:
- meta:

  roleBindings:
  - role: organization.view
    subjects:
    - kind: USER
      name: mjames@developerthejameshome.onmicrosoft.com