fullName:
  managementClusterName: aws-hosted
  name: tmc-testing-cluster
  orgId: 86514df0-46a7-4b33-857d-954ba2970773
  provisionerName: tmc-aws-provisioner
spec:
  clusterGroupName: development-cluster-group
  tkgAws:
    distribution:
      provisionerCredentialName: tmc-aws-credentials
      region: us-east-1
      version: 1.20.11-1-amazon2
    settings:
      network:
        cluster:
          pods:
          - cidrBlocks: 192.168.0.0/16
          services:
          - cidrBlocks: 10.96.0.0/12
        provider:
          vpc:
            cidrBlock: 10.0.0.0/16
      security:
        sshKey: tanzu-operations-us-east-1
    topology:
      controlPlane:
        availabilityZones:
        - us-east-1a
        instanceType: m5.large
type:
  kind: Cluster
  package: vmware.tanzu.manage.v1alpha1.cluster
  version: v1alpha1