fullName:
  name: tanzu-service-mesh
  clusterName: tmc-development-cluster
  managementClusterName: attached
  provisionerName: attached
spec:
  configurations:
    clusterName: tmc-development-cluster
    enableNamespaceExclusions: true
  secrets:
    token: REDACTED

