fullName:
  name: production-app
  clusterName: tmc-production-cluster
  managementClusterName: attached
  provisionerName: attached
meta:
  annotations:
    vmware.tanzu.manage.template: default
  description: ""
  labels:
    tier: app
spec:
  workspaceName: app-workspace
type:
  kind: Namespace
  package: vmware.tanzu.manage.v1alpha1.cluster.namespace
  version: v1alpha1
  