fullName:
  name: network-policy
  workspaceName: app-workspace
spec:
  input:
    rules:
    - ruleSpec:
      - namespaceSelector:
        - key: tier
          value: app
      - podSelector:
        - key: tier
          value: app
    toPodLabels:
    - key: tier
      value: data
  recipe: custom-ingress
  recipeVersion: v1
  type: network-policy