fullName:
  name: network-policy
  workspaceName: network-workspace
spec:
  input:
    rules:
    - ruleSpec:
      - podSelector:
        - key: tier
          value: app
    toPodLabels:
    - key: tier
      value: data
  recipe: custom-ingress
  recipeVersion: v1
  type: network-policy