apiVersion: apps/v1
kind: Deployment
metadata:
  name: quota-within
  labels:
    app: quota-within
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quota-within
  template:
    metadata:
      labels:
        app: quota-within
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "512Mi"
            cpu: "150m"
          limits:
            memory: "1G"
            cpu: "200m"
