fullName:
  name: registry
  clusterName: aks-registry-and-network-cluster
  managementClusterName: attached
  provisionerName: attached
meta:
  annotations:
    vmware.tanzu.manage.template: default
  description: ""
  labels: null
spec:
  workspaceName: registry-workspace
type:
  kind: Namespace
  package: vmware.tanzu.manage.v1alpha1.cluster.namespace
  version: v1alpha1
  