fullName:
  clusterGroupName: development-cluster-group
  name: security-policy
spec:
  input:
    allowHostNamespaceSharing: false
    allowHostNetwork: false
    allowPrivilegeEscalation: false
    allowPrivilegedContainers: false
    allowedHostPortRange:
      max: 65535
      min: 0
    allowedVolumes:
    - secret
    audit: false
    disableNativePsp: false
    linuxCapabilities:
      allowedCapabilities:
      - '*'
    runAsUser:
      ranges:
      - max: 1
        min: 0
      rule: MustRunAs
  recipe: custom
  recipeVersion: v1
  type: security-policy