fullName:
  clusterGroupName: quota-group
  name: security-policy
spec:
  input:
    allowHostNamespaceSharing: false
    allowHostNetwork: false
    allowPrivilegeEscalation: false
    allowPrivilegedContainers: false
    allowedHostPortRange:
      max: 65535
      min: 0
    allowedVolumes:
    - hostPath
    audit: false
    disableNativePsp: false
    linuxCapabilities:
      allowedCapabilities:
      - '*'
    runAsUser:
      ranges:
      - max: 65535
        min: 0
      rule: RunAsAny
  recipe: custom
  recipeVersion: v1
  type: security-policy